### PR TITLE
close all tabs more reliably

### PR DESCRIPTION
**Pull request by mbektasbbg**
existing logic using iterators is sometimes failing

### CODE REVIEW

**Review by jasongrout — APPROVED** [review]
Looks good to me. Thanks!

**Comment by jasongrout** [comment]
In particular, the iterator approach before this I think may run into issues where you are modifying the sequence as you are iterating through it, leading to skipping some items or closing some items inadvertently.

**Comment by mbektasbbg** [comment]
> In particular, the iterator approach before this I think may run into issues where you are modifying the sequence as you are iterating through it, leading to skipping some items or closing some items inadvertently.

thanks for the clarification @jasongrout!

**Comment by jasongrout** [comment]
For those listening, see the comment in JLab about that iterator issue, in the implementation of this close-all functionality: https://github.com/jupyterlab/jupyterlab/blob/136d2ec216ebfc429a696e6ee75fee5f8ead73e2/packages/application/src/shell.ts#L688-L696

(this code could also just call the shell's close all method directly, but invoking the command works as well).

**Comment by telamonian** [comment]
thanks for then notes, @jasongrout. I guess the other way to handle this would be to call `close` while iteratating over the list of tab widgets in reverse. But there doesn't seem to be any reverse iterator support in lumino (or in builtin javascript stuff like `forEach`). So it's a moot point

**Comment by jasongrout** [comment]
> But there doesn't seem to be any reverse iterator support in lumino

There is: https://github.com/jupyterlab/lumino/blob/master/packages/algorithm/src/retro.ts

**Comment by telamonian** [comment]
neat. I retract my earlier statement. Somehow I've never seen the `retro` stuff before

**Pull request merged**
