### PR TITLE
Add check release workflow on CI and CHANGELOG.md

### PR DESCRIPTION
**Pull request by jtpio**
In preparation for adopting (or at least testing) the Jupyter Releaser: #53 

- [x] Add Changelog
- [x] Add check release workflow
- [x] Switch to `yarn` to simplify the setup
- [x] Use the same `version` everywhere

### CODE REVIEW

**Comment by jtpio** [comment]
Added two new labels used by github-activity: https://github-activity.readthedocs.io/en/latest/#splitting-prs-by-tags-and-prefixes

image

**Comment by jtpio** [comment]
As a follow-up, we can then test a Draft Changelog workflow: https://github.com/jupyter-server/jupyter_releaser#typical-workflow

**Comment by jtpio** [comment]
https://github.com/jupyterlab/galata/issues/49 was suggesting switching to either `yarn` or `jlpm`, and #50 went for `jlpm`.

Here we change back to `yarn` to not introduce a new tool (plain yarn is enough) and make the use of the releaser simpler.

**Comment by jtpio** [comment]
cc @mbektas @fcollonval what do you think about adopting the releaser?

We could then try to go through the typical workflow and cut a new release:

- draft changelog for `3.0.11-3`
- draft release
- publish release

Detailed in https://github.com/jupyter-server/jupyter_releaser#typical-workflow

If that works we can then update `RELEASE.md` with the new instructions.

It it fails somewhere during the process we can always manually publish the new version.

**Review by blink1073 — APPROVED** [review]
Nice!

**Comment by fcollonval** [comment]
> what do you think about adopting the releaser?

I'm not against using it. But I'm convinced _galata helpers_ should integrate the core repo as soon as possible.

**Comment by jtpio** [comment]
> But I'm convinced _galata helpers_ should integrate the core repo as soon as possible.

For reference this is discussed in this issue: https://github.com/jupyterlab/jupyterlab/issues/10480

I also think it would be better to move galata there, not sure of when that would happen though.

**Comment by jtpio** [comment]
Let's give it a try and see how it goes.

**Pull request merged**
