### PR TITLE
Switch from npm to jlpm

### LINKED ISSUE #49: Switch from npm to yarn (or jlpm) for development
To make the tooling consistent across the `@jupyterlab` repositories, we should consider using `yarn` or `jlpm` instead of `npm` to manage dependencies and run scripts.

This would then also mean replacing the existing `package-lock.json` by a new `yarn.lock`.

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #49 

- Switch from `npm` to `jlpm`
- Read `@jupyterlab/application` version from `yarn.lock`
- Update docs

### CODE REVIEW

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio

**Comment by fcollonval** [comment]
Do you plan to add the linter in this PR or to left it aside? Let me know if you want me to do it.

**Comment by jtpio** [comment]
And yes a PR would be really nice, thanks!

**Comment by fcollonval** [comment]
> I would like to cut a new release right after with this change and #45

:+1:

**Comment by mbektas** [comment]
@jtpio I can't get tests to run properly with these changes. Could you please check? Following instructions here https://github.com/jupyterlab/galata#build-and-run-test-project gives the error: `page.addScriptTag: ENOENT: no such file or directory, open '.../galata/packages/galata/lib-inpage/inpage.js'`

Also, using `jlpm` is requiring a python environment with jupyterlab installed. Users of Galata could access jlab instance running remotely / in a container etc., so they weren't required to have jlab on their test environment.

**Comment by mbektas** [comment]
I am also noticing that `lib` directory is ending up at root directory after `lerna run build` instead of `packages/galata`. Because of that, published package doesn't contain lib directory. Release `3.0.11-1` doesn't contain lib directory for example.

**Comment by mbektas** [comment]
https://github.com/jupyterlab/galata/pull/62 fixed the `lib` output location

**Comment by jtpio** [comment]
Thanks @mbektas :+1: 

> Also, using `jlpm` is requiring a python environment with jupyterlab installed. Users of Galata could access jlab instance running remotely / in a container etc., so they weren't required to have jlab on their test environment.

`jlpm` would be for development only, and users can still use the published version of Galata independently?

Also I think it would be fine to use `yarn` instead of `jlpm` if needed for development.

**Pull request merged**
